apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.aws.snssqs
  version: v1
  metadata:
  - name: awsRegion
    value: us-east-1
  - name: topicArn
    value: arn:aws:sns:us-east-1:424987806936:orders
# Note: This component relies on IRSA (ServiceAccount mapping to IAM role). No accessKey/secret is provided.
